Add CI check for Drizzle migrations (#128)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -136,6 +136,41 @@ jobs:
             exit 1
           fi
 
+  drizzle-migrations:
+    needs: lockfile
+    runs-on: ubuntu-latest
+    env:
+      # Dummy DATABASE_URL
+      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
+    steps:
+      - uses: actions/checkout@v5
+      - uses: oven-sh/setup-bun@v2
+        with:
+          bun-version: 1.3.2
+
+      - name: Cache bun modules
+        uses: actions/cache@v4
+        with:
+          path: *bun-cache-paths
+          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-bun-
+
+      - name: Install dependencies
+        run: bun install --frozen-lockfile
+
+      - name: Check Drizzle migrations are up to date
+        run: |
+          bun run --cwd dimp-server drizzle-kit generate --config=drizzle.config.ts
+
+          git status --porcelain
+          if test -z "$(git status --porcelain)"; then
+            echo "Drizzle migrations are up to date ✔"
+          else
+            echo "::error::❌ Drizzle migrations are out of date. Please generate a migration using 'bun run --cwd dimp-server drizzle-kit generate --name <migration_name>'."
+            exit 1
+          fi
+
   auth-lint:
     needs: lockfile
     runs-on: ubuntu-latest
@@ -262,6 +297,7 @@ jobs:
         prettier,
         graphql-schema,
         graphql-codegen,
+        drizzle-migrations,
         auth-lint,
         bot-lint,
         dashboard-lint,
